### ISSUE TITLE
Only one usage of each socket error on emulator.

### ISSUE THREAD

**Issue by agentsmith170390** [ailen0ada/UWP.SSDP.Sample#1]
Hi! I have got this error running on blank  x86 emulator in Visual Studio 2015 Community Edition.
![image](https://cloud.githubusercontent.com/assets/19255175/15177561/62b39f68-1779-11e6-831e-f0989f0f3d26.png)
On real device it works fine. Looks like something else uses a socket on blank emulator, but i have no idea...

**Comment by ailen0ada** [comment]
@agentsmith170390 Have you solved your question? Feel free to ask me if you have any queries.

**Comment by agentsmith170390** [comment]
Disabling this windows services on PC solved this problem: SSDPSRV, upnphost.
